export const FETCH_CURRENT_USER_REQUEST = 'FETCH_CURRENT_USER_REQUEST';
export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS';
export const FETCH_CURRENT_USER_FAIL = 'FETCH_CURRENT_USER_FAIL';
export const FETCH_SAVED_TRACKS_REQUEST = 'FETCH_SAVED_TRACKS_REQUEST';
export const FETCH_SAVED_TRACKS_SUCCESS = 'FETCH_SAVED_TRACKS_SUCCESS';
export const FETCH_SAVED_TRACKS_FAIL = 'FETCH_SAVED_TRACKS_FAIL';
